-- MYSQL 8
CREATE DATABASE IF NOT EXISTS test COLLATE utf8mb4_0900_ai_ci;
USE test;

CREATE TABLE IF NOT EXISTS contacts(
	id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    email VARCHAR(200),
    birtdate DATE,
    cpf VARCHAR(15),
    cellphone VARCHAR(17) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME,
    PRIMARY KEY(id)
);

SELECT * FROM users;
-- REPRESENTAÇÃO DO DATABASE E TABLE
-- FIZ PELA APLICAÇÃO (MIGRATIONS)